### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by EnderGirl1500** [GabrielOlvH/Mo-Colors#10]
When I go to the tools page on the creative mod, the game crashes. When I uninstalled this mod, the problem stopped happening.

**Comment by RyzenFromFire** [comment]
Seconding this issue, can reproduce locally and with a friend. The painter is the problem, it generates an NPE - my guess is that somehow the Tools page thinks it has more rows to display than it actually does. Perhaps an off-by-one error. Posting relevant part of crash log here before I take a look at the code.

```
[19:19:13] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_757.method_3192(class_757.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:1548) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4021(class_918.java:306) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4026(class_918.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_36543(class_918.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_27951(class_918.java:335) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2385(class_465.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:679) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by EGOIST1372** [comment]
@RyzenFromFire @EnderGirl1500 mo colors mod need [indium](https://www.curseforge.com/minecraft/mc-mods/indium) mod to work. make sure you have it.

**Comment by EnderGirl1500** [comment]
Coming back after a year, I got Indium but REI doesn't work when Mo' Colors is installed
