### ISSUE TITLE
Game Crash on Server

### ISSUE THREAD

**Issue by LLLAlex915** [GabrielOlvH/Mo-Colors#19]
I'm trying to play Minecraft 1.20.1 with the Mo' Colors mod (version 1.6.0) on an Aternos server, but the server crashes every time I join. The same mod used to work fine on this server with previous Minecraft versions. However, the mod works without any issues in singleplayer mode.

### Server Log
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-03-22 20:13:26
Description: Exception in server tick loop

java.lang.NoSuchFieldError: backgroundPainter
	at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:27)
	at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12)
	at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:33)
	at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:53)
	at me.steven.mocolors.gui.PainterScreenHandler.<init>(PainterScreenHandler.java:34)
	at me.steven.mocolors.items.PainterItem.createMenu(PainterItem.java:54)
	at net.minecraft.class_3222.method_17355(class_3222.java:1034)
	at me.steven.mocolors.items.PainterItem.method_7836(PainterItem.java:46)
	at net.minecraft.class_1799.method_7913(class_1799.java:284)
	at net.minecraft.class_3225.method_14256(class_3225.java:290)
	at net.minecraft.class_3244.method_12065(class_3244.java:1177)
	at net.minecraft.class_2886.method_12550(class_2886.java:29)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-78-generic
	Java Version: 17.0.10, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1179947208 bytes (1125 MiB) / 2262827008 bytes (2158 MiB) up to 2306867200 bytes (2200 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7402P 24-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 48
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129821.19
	Virtual memory used (MB): 165545.41
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 1024.00
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx2200M -Xms1100M
	Fabric Mods: 
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		mocolors: Mo' Colors 1.6.0
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
	Server Running: true
	Player Count: 1 / 20; [class_3222['Benjamin_Lam'/2, l='ServerLevel[A World]', x=-1880.21, y=70.00, z=1127.08]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by LLLAlex915** [comment]
Update: the crash appears to be due to the Mo' Colors mod having an incompatibility with the version of the LibGui library it is using, causing it to refer to a GUI field that no longer exists when the painter item is used
