### ISSUE TITLE
Full Slabs Incompatibility

### ISSUE THREAD

**Issue by TheDerpu0ne** [GabrielOlvH/Mo-Colors#7]
if I were to place a vertical slab or put a slab on a slab the game crashes saying this:

**Comment by TheDerpu0ne** [comment]
(crash report:)
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 17/10/2021, 12:40
Description: Tesselating block in world - Indigo Renderer

java.lang.ClassCastException: class com.mojang.datafixers.util.Pair cannot be cast to class [I (com.mojang.datafixers.util.Pair is in unnamed module of loader 'app'; [I is in module java.base of loader 'bootstrap')
	at me.steven.mocolors.blocks.models.ColoredBrickSlabModel.emitBlockQuads(ColoredBrickSlabModel.java:32)
	at dev.micalobia.full_slabs.client.render.model.BasicModel.emitFabricModel(BasicModel.java:71)
	at dev.micalobia.full_slabs.client.render.model.BasicModel.emitModel(BasicModel.java:94)
	at dev.micalobia.full_slabs.client.render.model.FullSlabModel.emitBlockQuads(FullSlabModel.java:27)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zen000$hookChunkBuildTesselate(class_846.java:723)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:524)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:412)
	at net.minecraft.class_846.method_3627(class_846.java:189)
	at net.minecraft.class_761.method_3273(class_761.java:918)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zof000$redirectRenderingWorld(class_757.java:4122)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.steven.mocolors.blocks.models.ColoredBrickSlabModel.emitBlockQuads(ColoredBrickSlabModel.java:32)
	at dev.micalobia.full_slabs.client.render.model.BasicModel.emitFabricModel(BasicModel.java:71)
	at dev.micalobia.full_slabs.client.render.model.BasicModel.emitModel(BasicModel.java:94)
	at dev.micalobia.full_slabs.client.render.model.FullSlabModel.emitBlockQuads(FullSlabModel.java:27)

-- Block being tesselated --
Details:
	Block: Block{full_slabs:full_slab_block}[axis=y,light=0]
	Block location: World: (-214,65,-37), Section: (at 10,1,11 in -14,4,-3; chunk contains blocks -224,0,-48 to -209,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zen000$hookChunkBuildTesselate(class_846.java:723)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:524)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:412)
	at net.minecraft.class_846.method_3627(class_846.java:189)
	at net.minecraft.class_761.method_3273(class_761.java:918)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zof000$redirectRenderingWorld(class_757.java:4122)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheDerpu0ne'/1, l='ClientWorld minecraft:overworld', x=-213.76, y=66.50, z=-35.19]]
	Chunk stats: Client Chunks (ImmPtl) 4155
	Level dimension: minecraft:overworld
	Level spawn location: World: (-216,65,-40), Section: (at 8,1,8 in -14,4,-3; chunk contains blocks -224,0,-48 to -209,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 24463 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 771475520 bytes (735 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4454
	Graphics card #1 name: NVIDIA GeForce 840M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1341
	Graphics card #1 versionInfo: DriverVersion=21.21.13.7654
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 15777.92
	Virtual memory used (MB): 12185.30
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 1245.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		apoli: Apoli 2.0.3
		appleskin: AppleSkin mc1.17-2.1.2
		calio: Calio 1.0.3
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		chipped: Chipped 1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		clumps: Clumps fabric-1.17.1-7.0.4
		colorutility: ColorUtility 2.0.1
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		full_slabs: FullSlabs 3.2.0
		imm_ptl_core: Immersive Portals Core 0.20
		immersive_portals: Immersive Portals 0.20
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libgui: LibGui 4.1.1+1.17.1-rc1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		minecraft: Minecraft 1.17.1
		mocolors: Mo' Colors 1.2.2
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		origins: Origins 1.1.2
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		spruceui: SpruceUI 3.2.0+1.17
		statement: Statement 4.1.3+1.14.4-1.17.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		worldedit: WorldEdit 7.2.6+4b2d1e7
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce 840M/PCIe/SSE2 GL version 3.2.0 NVIDIA 376.54, NVIDIA Corporation
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Player Count: 1 / 8; [class_3222['TheDerpu0ne'/1, l='ServerWorld minecraft:overworld phrogs and tods', x=-213.76, y=66.50, z=-35.19]]
	Data Packs: vanilla, Fabric Mods

**Comment by EGOIST1372** [comment]
@TheDerpu0ne mo colors mod need [indium](https://www.curseforge.com/minecraft/mc-mods/indium) mod to work. make sure you have it.
