### ISSUE TITLE
Cannot render mod related items: crashes when trying to load sprite

### ISSUE THREAD

**Issue by WilliamPiette** [GabrielOlvH/Mo-Colors#9]
So I got a crash in my creative world when checking out the mod (had a fair few others installed however, including sodium, iris shaders and some content-related ones). I searched for the items writing "paint" in the search bar. As soon as I got to "pai", game crashed. encountering the sprites in REI also causes a crash. Here's the error:

[17:23:03] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_757.method_3192(class_757.java:884) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:1048) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4021(class_918.java:306) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4026(class_918.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_36543(class_918.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_27951(class_918.java:335) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2385(class_465.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:681) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:875) ~[client-intermediary.jar:?]
	... 10 more

_____________________________
I'm not often available, but if you have additionnal questions, I'll try and respond as soon as I see it.
additionnal mods:
fabric lang kotlin, visuality, iluminations, iris, sodium, ForgeConfigAPIPort, backslot, continuity
Libraries:
architectury, geckolib, libraryFerret, owo lib, puzzlesLib.

No shaders running at the moment of crash. 
Thanks for reading and have a good day!

**Comment by EGOIST1372** [comment]
@WilliamPiette  mo colors mod need [indium](https://www.curseforge.com/minecraft/mc-mods/indium) mod to work. make sure you have it.
